-- ---------------------------------------------------------------------------
-- 0003_gowid_source_column
-- Adds `source` column to expenseone.gowid_transactions and replaces the
-- single-column unique constraint on gowid_expense_id with a composite
-- unique on (source, gowid_expense_id). Prevents collisions between GoWid
-- and Codef/FinanceOne integer ID namespaces.
-- ---------------------------------------------------------------------------

ALTER TABLE expenseone.gowid_transactions
  ADD COLUMN IF NOT EXISTS source varchar(16) NOT NULL DEFAULT 'gowid';

-- Drop the old single-column unique. Constraint name is auto-generated by
-- Postgres at create time; resolve it dynamically to be safe.
DO $$
DECLARE
  cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_constraint
  WHERE conrelid = 'expenseone.gowid_transactions'::regclass
    AND contype = 'u'
    AND conkey = ARRAY[
      (SELECT attnum FROM pg_attribute
        WHERE attrelid = 'expenseone.gowid_transactions'::regclass
          AND attname = 'gowid_expense_id')
    ]::int2[];

  IF cname IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE expenseone.gowid_transactions DROP CONSTRAINT %I',
      cname
    );
  END IF;
END
$$;

-- Add composite unique index — matches Drizzle schema definition.
CREATE UNIQUE INDEX IF NOT EXISTS idx_gowid_tx_source_upstream
  ON expenseone.gowid_transactions (source, gowid_expense_id);
